FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

ARG PROJECT

# copy the whole solution
COPY . .

WORKDIR "/src/${PROJECT}"

RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
ARG PROJECT
ENV PROJECT=$PROJECT
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["/bin/sh", "-c", "dotnet \"${PROJECT##*/}.dll\""]
